[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]",
    # Removing "setuptools_scm_git_archive" becauses it causes pkg_resources error with setuptools 82+
    # "setuptools_scm_git_archive",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
